<script setup>
import { ref, watch, computed } from 'vue';
import AdminLayout from '@/Layouts/AdminLayout.vue';
import { Head, useForm, usePage } from '@inertiajs/vue3';
import { 
    ChartBarIcon, DocumentTextIcon, FlagIcon, 
    PaperAirplaneIcon, CheckCircleIcon, PhotoIcon, PaperClipIcon, XMarkIcon, LinkIcon,
    BuildingLibraryIcon, PlusIcon, TrashIcon
} from '@heroicons/vue/24/outline';
import InputError from '@/Components/InputError.vue';

defineOptions({ layout: AdminLayout });
const props = defineProps({ profile: Object });

const page = usePage();
const showNotification = ref(false);
const notificationMessage = ref('');
const flashSuccess = computed(() => page.props.flash?.success);

watch(flashSuccess, (message) => {
    if (message) {
        notificationMessage.value = message;
        showNotification.value = true;
        setTimeout(() => showNotification.value = false, 3000);
    }
}, { immediate: true });

const activeTab = ref('statistik');
const tabs = [
    { id: 'statistik', name: 'Statistik Data', icon: ChartBarIcon },
    { id: 'tugas', name: 'Tugas & Fungsi', icon: DocumentTextIcon },
    { id: 'visi', name: 'Visi & Misi', icon: FlagIcon },
    { id: 'fasilitas', name: 'Fasilitas Kampus', icon: BuildingLibraryIcon },
    { id: 'bagan', name: 'Bagan Organisasi', icon: PhotoIcon },
    { id: 'tautan', name: 'Tautan Eksternal', icon: LinkIcon }, 
];

const fileInput = ref(null);

const form = useForm({
    _method: 'PUT', 
    content: {
        statistik: props.profile?.content?.statistik || { deskripsi: '', data: [] },
        tugas_fungsi: props.profile?.content?.tugas_fungsi || { tugas: '', fungsi: [] },
        visi_misi: props.profile?.content?.visi_misi || { visi: '', misi_tagline: '', misi: [] },
        bagan_organisasi: props.profile?.content?.bagan_organisasi || 'images/bagan-organisasi.webp',
        pmb_link: props.profile?.content?.pmb_link || '', 
        tracer_study_link: props.profile?.content?.tracer_study_link || '',
        fasilitas: props.profile?.content?.fasilitas || []
    },
    bagan_image: null
});

const handleImageChange = (event) => {
    const target = event.target;
    if (target.files && target.files[0]) {
        form.bagan_image = target.files[0];
    } else {
        form.bagan_image = null;
    }
};

const clearImage = () => {
    form.bagan_image = null;
    if (fileInput.value) {
        fileInput.value.value = '';
    }
};

const addFasilitas = () => {
    form.content.fasilitas.push({ nama: '', deskripsi: '', gambar: '' });
};

const removeFasilitas = (index) => {
    form.content.fasilitas.splice(index, 1);
};

const handleFasilitasImageChange = (event, index) => {
    const target = event.target;
    if (target.files && target.files[0]) {
        form.content.fasilitas[index].gambar = target.files[0];
    }
};

const getImageUrl = (path) => {
    if (!path) return null;
    if (typeof path === 'object') return URL.createObjectURL(path);
    if (path.startsWith('http')) return path;
    if (path.startsWith('images/')) return `/${path}`; 
    return `/storage/${path}`; 
};

const isAutoGeneratedStat = (label) => {
    if (!label) return false;
    const lowerLabel = label.toLowerCase();
    return lowerLabel.includes('dosen') || 
           lowerLabel.includes('tendik') || 
           lowerLabel.includes('kependidikan') || 
           lowerLabel.includes('s1') || 
           lowerLabel.includes('s2') || 
           lowerLabel === 'program studi' || 
           lowerLabel === 'prodi' ||
           lowerLabel.includes('alumni') || 
           lowerLabel.includes('lulusan') ||
           lowerLabel === 'jurusan'; 
};

const submit = () => {
    form.clearErrors();
    let firstErrorTab = null;

    if (!form.content.statistik.deskripsi) {
        form.setError('content.statistik.deskripsi', 'Deskripsi halaman statistik wajib diisi.');
        if (!firstErrorTab) firstErrorTab = 'statistik';
    }
    form.content.statistik.data.forEach((stat, index) => {
        if (!stat.angka) {
            form.setError(`content.statistik.data.${index}.angka`, 'Angka wajib diisi.');
            if (!firstErrorTab) firstErrorTab = 'statistik';
        } else if (isNaN(stat.angka)) {
            form.setError(`content.statistik.data.${index}.angka`, 'Harus berupa angka.');
            if (!firstErrorTab) firstErrorTab = 'statistik';
        }
        if (!stat.label) {
            form.setError(`content.statistik.data.${index}.label`, 'Label wajib diisi.');
            if (!firstErrorTab) firstErrorTab = 'statistik';
        }
    });

    if (!form.content.tugas_fungsi.tugas || form.content.tugas_fungsi.tugas.trim().length < 10) {
        form.setError('content.tugas_fungsi.tugas', 'Tugas fakultas wajib diisi dengan jelas (minimal 10 karakter).');
        if (!firstErrorTab) firstErrorTab = 'tugas';
    }
    form.content.tugas_fungsi.fungsi.forEach((func, index) => {
        if (!func.judul || func.judul.trim().length < 3) {
            form.setError(`content.tugas_fungsi.fungsi.${index}.judul`, 'Judul fungsi wajib diisi (minimal 3 karakter).');
            if (!firstErrorTab) firstErrorTab = 'tugas';
        }
        if (!func.deskripsi || func.deskripsi.trim().length < 10) {
            form.setError(`content.tugas_fungsi.fungsi.${index}.deskripsi`, 'Deskripsi fungsi wajib diisi dengan jelas (minimal 10 karakter).');
            if (!firstErrorTab) firstErrorTab = 'tugas';
        }
    });

    if (!form.content.visi_misi.visi) {
        form.setError('content.visi_misi.visi', 'Visi fakultas wajib diisi.');
        if (!firstErrorTab) firstErrorTab = 'visi';
    }
    if (!form.content.visi_misi.misi_tagline) {
        form.setError('content.visi_misi.misi_tagline', 'Tagline misi wajib diisi.');
        if (!firstErrorTab) firstErrorTab = 'visi';
    }
    form.content.visi_misi.misi.forEach((m, index) => {
        if (!m.huruf) {
            form.setError(`content.visi_misi.misi.${index}.huruf`, 'Wajib.');
            if (!firstErrorTab) firstErrorTab = 'visi';
        } else if (!/^[A-Za-z]$/.test(m.huruf)) {
            form.setError(`content.visi_misi.misi.${index}.huruf`, 'Harus 1 Huruf.');
            if (!firstErrorTab) firstErrorTab = 'visi';
        }

        if (!m.teks) {
            form.setError(`content.visi_misi.misi.${index}.teks`, 'Misi wajib diisi.');
            if (!firstErrorTab) firstErrorTab = 'visi';
        }
    });

    form.content.fasilitas.forEach((f, index) => {
        if (!f.nama) { 
            form.setError(`content.fasilitas.${index}.nama`, 'Nama fasilitas wajib diisi.'); 
            if (!firstErrorTab) firstErrorTab = 'fasilitas'; 
        }
        if (!f.deskripsi) { 
            form.setError(`content.fasilitas.${index}.deskripsi`, 'Deskripsi fasilitas wajib diisi.'); 
            if (!firstErrorTab) firstErrorTab = 'fasilitas'; 
        }
        if (!f.gambar) { 
            form.setError(`content.fasilitas.${index}.gambar`, 'Gambar fasilitas wajib di-upload.'); 
            if (!firstErrorTab) firstErrorTab = 'fasilitas'; 
        }
    });

    if (form.bagan_image) {
        const allowedTypes = ['image/jpeg', 'image/png', 'image/webp'];
        if (!allowedTypes.includes(form.bagan_image.type)) {
            form.setError('bagan_image', 'Format file harus JPG, PNG, atau WEBP.');
            if (!firstErrorTab) firstErrorTab = 'bagan';
        } else if (form.bagan_image.size > 2 * 1024 * 1024) {
            form.setError('bagan_image', 'Ukuran file maksimal 2MB.');
            if (!firstErrorTab) firstErrorTab = 'bagan';
        }
    }

    const strictUrlPattern = /^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{2,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$/i;

    if (!form.content.pmb_link) {
        form.setError('content.pmb_link', 'Tautan PMB wajib diisi.');
        if (!firstErrorTab) firstErrorTab = 'tautan';
    } else if (!strictUrlPattern.test(form.content.pmb_link)) {
        form.setError('content.pmb_link', 'Tautan tidak valid. Masukkan URL lengkap dengan domain (Contoh: https://pmb.itk.ac.id).');
        if (!firstErrorTab) firstErrorTab = 'tautan';
    }

    if (!form.content.tracer_study_link) {
        form.setError('content.tracer_study_link', 'Tautan Kuesioner Tracer Study wajib diisi.');
        if (!firstErrorTab) firstErrorTab = 'tautan';
    } else if (!strictUrlPattern.test(form.content.tracer_study_link)) {
        form.setError('content.tracer_study_link', 'Tautan tidak valid. Masukkan URL lengkap dengan domain (Contoh: https://docs.google.com/...).');
        if (!firstErrorTab) firstErrorTab = 'tautan';
    }

    if (firstErrorTab) {
        activeTab.value = firstErrorTab;
        return;
    }

    form.transform((data) => ({
        ...data,
        _method: 'put',
        active_tab: activeTab.value 
    })).post(route('admin.faculty-profiles.update'), {
        preserveScroll: true, 
        preserveState: true, 
        onSuccess: () => {
            notificationMessage.value = page.props.flash?.success || 'Berhasil disimpan!';
            showNotification.value = true;
            form.bagan_image = null; 
            if (fileInput.value) fileInput.value.value = '';
            setTimeout(() => showNotification.value = false, 3000);
        }
    });
};
</script>

<template>
  <Head title="Kelola Profil Fakultas" />
  <div>
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-gray-900">Kelola Tentang Fakultas</h1>
      <p class="mt-2 text-gray-600">Perbarui redaksi data statistik, fungsi, visi misi, fasilitas, dan bagan yang tampil pada halaman publik.</p>
    </div>

    <div class="mb-6 border-b border-gray-200 bg-white px-4 pt-2 rounded-t-2xl shadow-sm">
        <nav class="-mb-px flex space-x-8 overflow-x-auto" aria-label="Tabs">
            <button 
                v-for="tab in tabs" 
                :key="tab.id" 
                @click="activeTab = tab.id" 
                type="button"
                :class="[
                    activeTab === tab.id
                        ? 'border-primary text-primary'
                        : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300',
                    'group inline-flex items-center gap-2 py-4 px-1 border-b-2 font-bold text-sm whitespace-nowrap transition-colors'
                ]"
            >
                <component 
                    :is="tab.icon" 
                    :class="[
                        activeTab === tab.id ? 'text-primary' : 'text-gray-400 group-hover:text-gray-500',
                        'h-5 w-5 transition-colors'
                    ]" 
                />
                {{ tab.name }}
            </button>
        </nav>
    </div>

    <div class="w-full">
        <form @submit.prevent="submit" class="bg-white shadow-sm border border-gray-100 rounded-b-2xl rounded-tr-2xl flex flex-col min-h-[500px]" novalidate>
            <div class="p-8 flex-grow">
                
                <div v-show="activeTab === 'statistik'">
                    <h2 class="text-2xl font-bold mb-6">Statistik Fakultas</h2>
                    <div class="mb-6 bg-gray-50 p-6 rounded-2xl border border-gray-100">
                        <label class="block text-sm font-bold mb-2">Deskripsi Singkat Halaman <span class="text-red-500">*</span></label>
                        <input 
                            type="text" 
                            v-model="form.content.statistik.deskripsi" 
                            class="w-full rounded-xl py-3 transition-all duration-200"
                            :class="form.errors['content.statistik.deskripsi'] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white shadow-sm'"
                        >
                        <InputError :message="form.errors['content.statistik.deskripsi']" />
                    </div>
                    
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div v-for="(stat, index) in form.content.statistik.data" :key="index" class="bg-white p-5 border border-gray-200 rounded-2xl shadow-sm">
                            <label class="text-xs font-bold text-primary mb-3 block uppercase tracking-wider">Kotak Data {{ index + 1 }}</label>
                            <div class="flex gap-4 items-start">
                                <div class="w-1/3">
                                    <input 
                                        type="text" 
                                        v-model="stat.angka" 
                                        class="w-full text-lg font-bold rounded-xl py-3 transition-all duration-200 text-center"
                                        :class="[
                                            form.errors[`content.statistik.data.${index}.angka`] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white',
                                            isAutoGeneratedStat(stat.label) ? 'bg-gray-100 text-gray-500 cursor-not-allowed select-none' : ''
                                        ]"
                                        placeholder="Angka"
                                        :readonly="isAutoGeneratedStat(stat.label)"
                                    >
                                    <InputError :message="form.errors[`content.statistik.data.${index}.angka`]" />
                                </div>
                                <div class="w-full">
                                    <input 
                                        type="text" 
                                        v-model="stat.label" 
                                        class="w-full rounded-xl py-3 transition-all duration-200"
                                        :class="form.errors[`content.statistik.data.${index}.label`] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'"
                                        placeholder="Label (Mhs / Dosen / Dll)"
                                    >
                                    <InputError :message="form.errors[`content.statistik.data.${index}.label`]" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div v-show="activeTab === 'tugas'">
                    <h2 class="text-2xl font-bold mb-6">Tugas & Fungsi</h2>
                    <div class="space-y-8">
                        <div class="bg-gray-50 p-6 rounded-2xl border border-gray-100">
                            <label class="block text-sm font-bold mb-2">Tugas Fakultas (Paragraf) <span class="text-red-500">*</span></label>
                            <textarea 
                                v-model="form.content.tugas_fungsi.tugas" 
                                rows="4" 
                                class="w-full rounded-xl py-3 transition-all duration-200 shadow-sm"
                                :class="form.errors['content.tugas_fungsi.tugas'] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'"
                            ></textarea>
                            <InputError :message="form.errors['content.tugas_fungsi.tugas']" />
                        </div>

                        <hr class="border-gray-200">

                        <div class="space-y-5">
                            <h3 class="font-bold text-gray-700 bg-gray-50 p-4 rounded-xl border border-gray-200">Daftar Fungsi Fakultas</h3>
                            <div v-for="(func, index) in form.content.tugas_fungsi.fungsi" :key="index" class="bg-white p-5 border border-gray-200 rounded-2xl shadow-sm flex gap-5 items-start">
                                <div class="shrink-0 w-10 h-10 flex items-center justify-center bg-blue-50 text-primary font-bold rounded-xl text-lg">{{ index + 1 }}</div>
                                <div class="w-full space-y-4">
                                    <div>
                                        <input 
                                            type="text" 
                                            v-model="func.judul" 
                                            placeholder="Judul Fungsi" 
                                            class="w-full font-bold rounded-xl py-3 transition-all duration-200"
                                            :class="form.errors[`content.tugas_fungsi.fungsi.${index}.judul`] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'"
                                        >
                                        <InputError :message="form.errors[`content.tugas_fungsi.fungsi.${index}.judul`]" />
                                    </div>
                                    <div>
                                        <textarea 
                                            v-model="func.deskripsi" 
                                            rows="2" 
                                            placeholder="Deskripsi lengkap..." 
                                            class="w-full text-sm rounded-xl py-3 transition-all duration-200"
                                            :class="form.errors[`content.tugas_fungsi.fungsi.${index}.deskripsi`] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'"
                                        ></textarea>
                                        <InputError :message="form.errors[`content.tugas_fungsi.fungsi.${index}.deskripsi`]" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div v-show="activeTab === 'visi'">
                    <h2 class="text-2xl font-bold mb-6">Visi & Misi</h2>
                    <div class="space-y-8">
                        <div>
                            <label class="block text-sm font-bold mb-2">Teks Visi Fakultas <span class="text-red-500">*</span></label>
                            <textarea 
                                v-model="form.content.visi_misi.visi" 
                                rows="4" 
                                class="w-full rounded-xl py-4 font-medium text-lg leading-relaxed shadow-sm transition-all duration-200"
                                :class="form.errors['content.visi_misi.visi'] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'"
                            ></textarea>
                            <InputError :message="form.errors['content.visi_misi.visi']" />
                        </div>

                        <div class="bg-gray-50 p-6 rounded-2xl border border-gray-100">
                            <div class="mb-6">
                                <label class="block text-sm font-bold mb-1">Misi Tagline / Akronim <span class="text-red-500">*</span></label>
                                <input 
                                    type="text" 
                                    v-model="form.content.visi_misi.misi_tagline" 
                                    class="mt-1 py-3 text-sm rounded-xl w-72 transition-all duration-200 shadow-sm"
                                    :class="form.errors['content.visi_misi.misi_tagline'] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'"
                                >
                                <InputError :message="form.errors['content.visi_misi.misi_tagline']" />
                            </div>
                            
                            <div class="grid grid-cols-1 lg:grid-cols-2 gap-5">
                                <div v-for="(m, index) in form.content.visi_misi.misi" :key="index" class="flex gap-4 items-start bg-white p-4 border border-gray-200 rounded-2xl shadow-sm">
                                    <div class="flex-shrink-0">
                                        <input 
                                            type="text" 
                                            v-model="m.huruf" 
                                            maxlength="1"
                                            class="w-16 font-bold text-center rounded-xl py-3 uppercase transition-all duration-200"
                                            :class="form.errors[`content.visi_misi.misi.${index}.huruf`] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-blue-50 text-primary'"
                                        >
                                        <div v-if="form.errors[`content.visi_misi.misi.${index}.huruf`]" class="text-[10px] text-red-600 font-bold mt-1 text-center w-full break-words">
                                            {{ form.errors[`content.visi_misi.misi.${index}.huruf`] }}
                                        </div>
                                    </div>
                                    <div class="w-full">
                                        <input 
                                            type="text" 
                                            v-model="m.teks" 
                                            class="w-full rounded-xl py-3 text-sm transition-all duration-200"
                                            :class="form.errors[`content.visi_misi.misi.${index}.teks`] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'"
                                        >
                                        <InputError :message="form.errors[`content.visi_misi.misi.${index}.teks`]" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div v-show="activeTab === 'fasilitas'">
                    <div class="flex justify-between items-center mb-6">
                        <h2 class="text-2xl font-bold">Fasilitas & Lingkungan Kampus</h2>
                        <button type="button" @click="addFasilitas" class="flex items-center gap-2 px-4 py-2 bg-blue-50 text-primary font-bold rounded-xl hover:bg-blue-100 transition shadow-sm border border-blue-100">
                            <PlusIcon class="w-5 h-5" /> Tambah Fasilitas
                        </button>
                    </div>
                    <p class="text-gray-600 mb-6 bg-blue-50 p-4 rounded-xl text-sm border border-blue-100">Tambahkan fasilitas yang dimiliki oleh fakultas. Pada tampilan publik, urutan pertama dan urutan ke-6 ke atas akan otomatis ditampilkan dengan ukuran <i>card</i> yang lebih lebar agar tidak membosankan.</p>
                    
                    <div class="space-y-6">
                        <div v-for="(item, index) in form.content.fasilitas" :key="index" class="bg-gray-50 p-6 rounded-2xl border border-gray-200 relative group shadow-sm transition-all hover:shadow-md hover:border-blue-200">
                            
                            <button type="button" @click="removeFasilitas(index)" class="absolute -top-3 -right-3 w-8 h-8 flex items-center justify-center bg-red-100 text-red-600 rounded-full hover:bg-red-500 hover:text-white transition shadow-md z-10" title="Hapus Fasilitas">
                                <TrashIcon class="w-4 h-4" />
                            </button>

                            <div class="flex flex-col md:flex-row gap-6">
                                <div class="w-full md:w-1/3 shrink-0">
                                    <label class="block text-sm font-bold mb-2">Foto / Gambar <span class="text-red-500">*</span></label>
                                    
                                    <div v-if="getImageUrl(item.gambar)" class="mb-3">
                                        <img :src="getImageUrl(item.gambar)" class="w-full h-32 object-cover rounded-xl border border-gray-300 shadow-sm" alt="Preview">
                                    </div>
                                    
                                    <div class="relative flex items-center w-full rounded-xl border shadow-sm px-3 py-2 hover:bg-white transition"
                                         :class="form.errors[`content.fasilitas.${index}.gambar`] ? 'border-red-500 bg-red-50 text-red-900' : 'border-gray-300 bg-white'">
                                        <PaperClipIcon class="h-5 w-5 text-gray-400" />
                                        <span class="ml-2 text-xs truncate flex-1 text-gray-500" :class="{'text-red-700 font-bold': form.errors[`content.fasilitas.${index}.gambar`]}">
                                            {{ typeof item.gambar === 'object' && item.gambar !== null ? item.gambar.name : (item.gambar ? 'Gambar tersimpan...' : 'Pilih file...') }}
                                        </span>
                                        <input type="file" accept="image/*" @change="handleFasilitasImageChange($event, index)" class="absolute inset-0 w-full h-full opacity-0 cursor-pointer" />
                                    </div>
                                    <InputError :message="form.errors[`content.fasilitas.${index}.gambar`]" class="mt-1" />
                                </div>
                                <div class="w-full space-y-4">
                                    <div>
                                        <label class="block text-sm font-bold mb-1">Nama Fasilitas <span class="text-red-500">*</span></label>
                                        <input type="text" v-model="item.nama" placeholder="Contoh: Co Learning Space" class="w-full rounded-xl py-2.5 transition-all duration-200 shadow-sm"
                                               :class="form.errors[`content.fasilitas.${index}.nama`] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'">
                                        <InputError :message="form.errors[`content.fasilitas.${index}.nama`]" />
                                    </div>
                                    <div>
                                        <label class="block text-sm font-bold mb-1">Deskripsi Singkat <span class="text-red-500">*</span></label>
                                        <textarea v-model="item.deskripsi" rows="2" placeholder="Ruang nyaman untuk belajar bersama..." class="w-full rounded-xl py-2.5 text-sm transition-all duration-200 shadow-sm"
                                                  :class="form.errors[`content.fasilitas.${index}.deskripsi`] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'"></textarea>
                                        <InputError :message="form.errors[`content.fasilitas.${index}.deskripsi`]" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div v-if="form.content.fasilitas.length === 0" class="text-center py-10 bg-gray-50 rounded-2xl border-2 border-dashed border-gray-300 text-gray-500">
                            Belum ada data fasilitas. Klik tombol "Tambah Fasilitas" di atas.
                        </div>
                    </div>
                </div>

                <div v-show="activeTab === 'bagan'">
                    <h2 class="text-2xl font-bold mb-6">Bagan Organisasi</h2>
                    <div class="space-y-6">
                         <div class="bg-gray-50 p-6 rounded-2xl border border-gray-200">
                            
                            <div class="mb-6 flex flex-col md:flex-row gap-4 items-start" v-if="form.content.bagan_organisasi">
                                <div>
                                    <p class="text-sm text-gray-600 font-bold mb-3">Bagan Saat Ini:</p>
                                    <img :src="getImageUrl(form.content.bagan_organisasi)" alt="Bagan Organisasi" class="h-auto w-full max-w-lg object-contain rounded-xl border border-gray-300 shadow-sm bg-white p-3">
                                </div>
                            </div>

                            <label class="block text-sm text-gray-700 mb-2 font-bold">Upload Gambar Bagan Baru</label>
                            <div class="relative flex items-center w-full rounded-xl border shadow-sm px-4 py-3 hover:bg-gray-50 transition"
                                 :class="form.errors.bagan_image ? 'border-red-500 bg-red-50' : 'border-gray-300 bg-white'">
                                <PaperClipIcon :class="form.errors.bagan_image ? 'text-red-400' : 'text-gray-400'" class="h-6 w-6" />
                                <span class="ml-3 text-sm truncate flex-1 font-medium" :class="form.errors.bagan_image ? 'text-red-700' : 'text-gray-500'">
                                    {{ form.bagan_image ? form.bagan_image.name : 'Pilih file gambar baru...' }}
                                </span>
                                <button v-if="form.bagan_image" type="button" @click.prevent="clearImage" class="ml-2 p-1.5 text-red-500 hover:bg-red-100 rounded-lg relative z-10"><XMarkIcon class="w-5 h-5"/></button>
                                <input ref="fileInput" type="file" accept="image/*" @change="handleImageChange" class="absolute inset-0 w-full h-full opacity-0 cursor-pointer" :class="{'hidden': form.bagan_image}" />
                            </div>
                            <InputError :message="form.errors.bagan_image" />
                            <p class="text-xs text-gray-500 italic mt-3">Pastikan gambar memiliki background putih atau transparan untuk hasil terbaik. Format yang didukung: JPG, PNG, WEBP. Maksimal 2MB.</p>
                        </div>
                    </div>
                </div>

                <div v-show="activeTab === 'tautan'">
                    <h2 class="text-2xl font-bold mb-6">Pengaturan Tautan Eksternal</h2>
                    <div class="space-y-6">
                        <div class="bg-gray-50 p-6 rounded-2xl border border-gray-100">
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div>
                                    <label class="block text-sm font-bold mb-2">Tautan PMB (Penerimaan Mahasiswa Baru) <span class="text-red-500">*</span></label>
                                    <input 
                                        type="text" 
                                        v-model="form.content.pmb_link" 
                                        placeholder="Cth: https://pmb.itk.ac.id" 
                                        class="w-full rounded-xl py-3 transition-all duration-200 shadow-sm"
                                        :class="form.errors['content.pmb_link'] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'"
                                    >
                                    <InputError :message="form.errors['content.pmb_link']" />
                                </div>

                                <div>
                                    <label class="block text-sm font-bold mb-2">Tautan Kuesioner Tracer Study (Alumni) <span class="text-red-500">*</span></label>
                                    <input 
                                        type="text" 
                                        v-model="form.content.tracer_study_link" 
                                        placeholder="Cth: https://docs.google.com/forms/..." 
                                        class="w-full rounded-xl py-3 transition-all duration-200 shadow-sm"
                                        :class="form.errors['content.tracer_study_link'] ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50 text-red-900' : 'border-gray-300 focus:border-primary focus:ring-primary bg-white'"
                                    >
                                    <InputError :message="form.errors['content.tracer_study_link']" />
                                </div>
                            </div>

                            <p class="text-sm text-gray-600 mt-5 leading-relaxed">
                                <span class="font-bold">Informasi:</span> Tautan yang Anda masukkan di atas akan menjadi tujuan (link) ketika pengunjung mengklik tombol pada halaman terkait (seperti PMB atau Tracer Study). Pastikan tautan diawali dengan <code>http://</code> atau <code>https://</code>.
                            </p>
                        </div>
                    </div>
                </div>

            </div>

            <div class="bg-gray-50 px-8 py-5 border-t border-gray-100 rounded-b-2xl flex items-center justify-end shrink-0">
                <button type="submit" :disabled="form.processing" class="flex items-center justify-center gap-2 px-8 py-3.5 rounded-xl bg-primary text-white font-bold hover:bg-opacity-90 transition shadow-sm w-full sm:w-auto disabled:opacity-50">
                    <PaperAirplaneIcon class="w-5 h-5" /> <span>{{ form.processing ? 'Menyimpan...' : 'Simpan Perubahan' }}</span>
                </button>
            </div>
        </form>
    </div>

    <div v-if="showNotification" class="fixed top-5 right-5 z-50 transition-transform duration-300 ease-in-out">
        <div class="flex items-center gap-4 rounded-xl bg-green-600 p-4 text-white shadow-xl">
            <CheckCircleIcon class="h-8 w-8" />
            <p class="font-semibold">{{ notificationMessage }}</p>
        </div>
    </div>
  </div>
</template>